### ISSUE TITLE
Determining the requirements of the project 

### ISSUE THREAD

**Issue by hatice-ecevit-2016400138** [bounswe/bounswe2018group1#10]
We should discuss our project requirements. Please comment if you have any ideas (e.g. if you want anything to be added or be removed etc.) about requirements below.

Requirements

1.Functional Requirements
	
	1.1. User Requirements
		1.1.1. Unregistered Users
			1.1.1.1. Register: Unregistered users shall be able to register to the system.
				1.1.1.1.1. Registration form contains mandatory fields which are username, password and e-mail address
				1.1.1.1.2. Users shall be able to use authentication while registering(?)
		1.1.2. Registered Users
			1.1.2.1. Users shall be able to login
			1.1.2.2. Users shall be able to share memories
				1.1.2.2.1. Memories shall have a location information
				1.1.2.2.2. Memories shall have a time information
				1.1.2.2.3. Memories shall be able to contain photos
				1.1.2.2.4. Memories shall be able to contain audio
				1.1.2.2.5. Memories shall be able to contain a video
				1.1.2.2.6. Memories shall be able to contain a story
			1.1.2.3. Users shall be able to search in memories
				1.1.2.3.1. Users shall be able to search memories based on location
				1.1.2.3.2. Users shall be able to search memories based on username
				1.1.2.3.3. Users shall be able to search memories based on a specific string in stories (?)
			1.1.2.4. Users shall be able to change his/hers password and e-mail
			1.1.2.5. Users shall be able to leave a comment to a memory
			1.1.2.6. Users shall be able to like a memory
			1.1.2.7. Users shall be able to see his/hers memories
				1.1.2.7.1. Users shall be able to edit his/hers memories
				1.1.2.7.2. Users shall be able to delete his/hers memories
			1.1.2.7. Users shall be able to add annotations to the images of the memories
	
	1.2. System Requirements
		1.2.1. Memory Requirements
			1.2.1.1. A memory shall have a title
			1.2.1.2. A memory shall have a location
			1.2.1.3. W3C shall be used to store annotations
			1.2.1.4. System shall recommend users
			1.2.1.5. System shall recommend memories

2. Nonfunctional Requirements
	2.1. Security

**Comment by cemal-aytekin-2015400126** [comment]
What did you learn from customer? According to your knowledge after meeting with customer, what do you think about the requirements above? @eceatata @ahmetyalp @samedcildir

**Comment by cemal-aytekin-2015400126** [comment]
I think we should use "should be able to" in the following requirements instead of "shall be able to":

1.1.2.7.1. Users shall be able to edit his/hers memories 
1.1.2.7.2. Users shall be able to delete his/hers memories

**Comment by eceatata** [comment]
what is the exact difference between? Asistant said that you must be careful about shall and should usage.

**Comment by cemal-aytekin-2015400126** [comment]
we use shall for the mandatory requirements and should for the optional ones.

**Comment by yilmazvolkan** [comment]
@hatice-ecevit-2016400138  Is it possible to change the format since it is hard to distinguish headings and read requirements?
