### ISSUE TITLE
Research specification of annotation

### ISSUE THREAD

**Issue by buseece** [bounswe/bounswe2018group1#103]
We should start working on Annotation. @20.11.18, we need to have the initial implementation.

- [x] Research

- [x] How are we going to implement it?

- [x] Starting to implement

**Comment by eceatata** [comment]
There are some useful links about annotation: 
https://www.w3.org/TR/annotation-model/
https://www.w3.org/annotation/

**Comment by eceatata** [comment]
there is a very useful link about annotation:
https://github.com/susielu/react-annotation

**Comment by eceatata** [comment]
bunu baya elle deneyebiliyoruz:
https://react-annotation.susielu.com/

**Comment by ziyaakyuz2253** [comment]
Benim baktığım yerde burasıydı gayet güzel anlatmış

27 Kas 2018 Sal, saat 12:46 tarihinde Ece Ata <notifications@github.com>
şunu yazdı:

**Comment by eceatata** [comment]
https://docs.genius.com/#annotations-h2

**Comment by buseece** [comment]
For images we are going to use DataPositionSelector, it gives byte in bitstream level. Example :
 {
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno25",
  "type": "Annotation",
  "body": "http://example.org/note1",
  "target": {
    "source": "http://example.org/diskimg1",
    "selector": {
      "type": "DataPositionSelector",
      "start": 4096,
      "end": 4104
    }
  }
}

And for text we will use TextPositionSelector, example look for text annotation:

{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno24",
  "type": "Annotation",
  "body": "http://example.org/review1",
  "target": {
    "source": "http://example.org/ebook1",
    "selector": {
      "type": "TextPositionSelector",
      "start": 412,
      "end": 795
    }
  }
}.

**Comment by buseece** [comment]
Update about selectors, as I realized in conformance section, DataPositionSelector is not compliant with our image data. Therefore It would be better to use FragmentSelector. We can use FragmentSelector for both text and images.

**Comment by buseece** [comment]
Plain Text | http://tools.ietf.org/rfc/rfc5147 | [rfc5147] Example: char=0,10
-- | -- | --

Media | http://www.w3.org/TR/media-frags/ | [media-frags] Example: xywh=50,50,640,480
-- | -- | --

**Comment by buseece** [comment]
Annotation is implemented different than web annotation model.
