### ISSUE TITLE
Adding '1970s' specification to memory 

### ISSUE THREAD

**Issue by buseece** [bounswe/bounswe2018group1#110]
Currently our system only gets start date and end date while creating the memory. We need to improve it so that user can also give a period (e.g. 2000s, 1970s) as time.

**Comment by denizetkar** [comment]
My suggestion to format the dates is the following:

1. For exact dates and intervals, we will store our data as usual,
2. For "rough" dates, we can store a field called resolution which can tell us how accurate the date is in terms of a year.
For example, if someone wants to store an exact date of 27th of November 2018 the memory will have fields:
`{"startDateDD": 27,
  "startDateHH": 0,
  "startDateMM": 11,
  "startDateYYYY": 2018,
  "resolution": 0}`
If another person wanted to store a time that is not exact but within a certain year, let's say the year 2018 then the fields will be:
`{"startDateDD": 0,
  "startDateHH": 0,
  "startDateMM": 0,
  "startDateYYYY": 2018,
  "resolution": 1}`
If in a similar case someone wanted to store a rough date within a certain decade, let's say 1970s then it will be:
`{"startDateDD": 0,
  "startDateHH": 0,
  "startDateMM": 0,
  "startDateYYYY": 1970,
  "resolution": 10}`
If the memory is roughly within a century:
`{"startDateDD": 0,
  "startDateHH": 0,
  "startDateMM": 0,
  "startDateYYYY": 1900,
  "resolution": 100}`
