### ISSUE TITLE
Map doesn't show up in memory create page (android)!

### ISSUE THREAD

**Issue by denizetkar** [bounswe/bounswe2018group1#113]
**Test environment:**

- Android 8.0 (Google APIs)
- API version 26
- CPU x86_64

**How to reproduce (android):**

1. Log in,
2. Navigate to "CREATE" tab,
3. Click "Add Location" button,
4. Click "M" button.

**Expected behaviour:**

A google map of world should appear to pin a location.

**Actual behaviour:**

![bug](https://user-images.githubusercontent.com/25102252/49098934-2a595280-f281-11e8-918e-957c082321d8.png)

**Comment by emrebil** [comment]
Which phone is that?
