### ISSUE TITLE
Malicious package warning on npm

### ISSUE THREAD

**Issue by UtkuBozdogan** [bounswe/bounswe2018group1#127]
When I tried to run the latest version of the project, I got the below warning. The 2 low and 1 high vulnerabilities were present before, but now we have a critical as well. I got worried because of the "malicious" searched a bit and found [this link](https://www.npmjs.com/advisories/737) Turns out this steals your bitcoins, we need to fix this ASAP!
![theytookourbitcoins](https://user-images.githubusercontent.com/25617689/49699816-eeaa7b00-fbe6-11e8-869c-f8057cb1b8e7.PNG)

**Comment by UtkuBozdogan** [comment]
Update: I might have solved it, could you please pull the new version and run npm-install then npm-start and tell me how it does?

**Comment by eceatata** [comment]
It's solved.
