### ISSUE TITLE
Not return memory id in get memory request

### ISSUE THREAD

**Issue by denizetkar** [bounswe/bounswe2018group1#133]
In each memory response, we need the memory ID in order to be able to later 'GET' it.

**Comment by eceatata** [comment]
He is right.

**Comment by eceatata** [comment]
{
  "content": [
    {
      "dateOfCreation": "2018-12-15T07:56:05.106Z",
      "endDateDD": 0,
      "endDateHH": 0,
      "endDateMM": 0,
      "endDateYYYY": 0,
      "headline": "string",
      "listOfItems": [
        {
          "body": "string",
          "id": 0,
          "url": "string"
        }
      ],
      "listOfLocations": [
        {
          "latitude": 0,
          "locationName": "string",
          "longitude": 0
        }
      ],
      "listOfTags": [
        {
          "text": "string"
        }
      ],
      "startDateDD": 0,
      "startDateHH": 0,
      "startDateMM": 0,
      "startDateYYYY": 0,
      "updatedTime": "2018-12-15T07:56:05.106Z",
      "userFirstName": "string",
      "userId": 0,
      "userLastName": "string",
      "userNickname": "string",
      "userProfilePicUrl": "string"
    }
  ],
  "first": true,
  "last": true,
  "number": 0,
  "numberOfElements": 0,
  "pageable": {
    "offset": 0,
    "pageNumber": 0,
    "pageSize": 0,
    "paged": true,
    "sort": {
      "sorted": true,
      "unsorted": true
    },
    "unpaged": true
  },
  "size": 0,
  "sort": {
    "sorted": true,
    "unsorted": true
  },
  "totalElements": 0,
  "totalPages": 0
}

There is no id for memories.
