### ISSUE TITLE
Editing the readme file

### ISSUE THREAD

**Issue by cemal-aytekin-2015400126** [bounswe/bounswe2018group1#14]
We discuss about our readme file and decided it is not sufficient and clear. Therefore we should edit and review it.

**Comment by yilmazvolkan** [comment]
Created team joint [logo](https://github.com/bounswe/bounswe2018group1/blob/master/resources/group_icon.jpg).

**Comment by yilmazvolkan** [comment]
Searched good readme file examples on Github and creating a new one suitable for our project. It is [here](https://github.com/bounswe/bounswe2018group1/blob/master/README.md).
