### ISSUE TITLE
Requirements Feedback

### ISSUE THREAD

**Issue by cemal-aytekin-2015400126** [bounswe/bounswe2018group1#19]
Instructor Can Tunca posted a new Note. 

Requirements Feedback
* [x] Typo in 1.1.1

* [x] The requirements about unregistered users should also cover what they actually can or can't do. Like, are they allowed to search, browse for memories (which they should be able to), or are they allowed to create new memories (which they should not).

* [x] It is a good idea to further organize requirements under different sections for each functionality. For instance, all the requirements related to memories may go under a Memory section. Or similarly req.s about profile pages can go under Profile, and so on. After you do this, maybe you can move all the req.s under 1.1.1 and 1.1.2 to their respective sections and only leave the items that describe the registered/guest users' capabilities under these two sections.

* [x] For req.s like 1.1.2.2.1., it is not clear how that specific data will be added to the system. We actually expect users to add information like location, photos, story etc. So, you should revise these requirements like "The users shall be able to add location information...".

* [x] In addition to search, requirements about content (memory) browsing are missing. We should have requirements that specify how a user is allowed to sort memories based on specific criteria (like recency, popularity etc.), and view the filtered content in a newsfeed-like format.

* [x] About req. 1.1.2.8: Please elaborate on which type of content can be annotated, like can we annotate text, images, comments, stories, locations (map)? (I added slides about annotations in Resources section, you can see that to get some ideas)

* [x] One important feature we want is a map-view (probably on the homepage), that shows all the previously added memories as pins on the map, so that a user can go to a specific location and see all the memories there. (Kind of like Google Maps where you see all the points of interest when you zoom in on an area)

* [x] About 1.1.2.2.2: Please elaborate on what you mean by time. Is it the time of the memory or the date that the memory is added to the system?

* [x] About 1.2.1.1.1: We have so many other information we can use for recommendations like location, time, the story text itself. Please extend this requirement to contain such information.

* [x] About 1.1.2.7: Yes, we want this, but we also want other users to be able to see each other's memories, kind of like profile pages. So you should add requirements about user profiles.

* [x] Memory description in glossary: It should also contain some explanation on what a memory is (or should be) about. Like what kind of content do we expect the users to add? (Basically give us a brief idea about what this project is all about) #

**Comment by yilmazvolkan** [comment]
We reviewed each feadback and upragade our [Requirements](https://github.com/bounswe/bounswe2018group1/wiki/Requirements) accordingly. It is up-to-date now.
