### ISSUE TITLE
Requirement Discussion

### ISSUE THREAD

**Issue by cemal-aytekin-2015400126** [bounswe/bounswe2018group1#21]
* We should discuss about  **1.1.7 Annotations**  in the requirements and elaborate on which type of content can be annotated, like can users annotate text, images, comments, stories, locations (map)? 

(There is a slide about annotations in Resources section in piazza, we can see that to get some ideas)

* We should discuss about  **1.1.6. Profile Page Requirements**  in the requirements.

* We should rewrite Memory definition in glossary based on customer feedback.

* We should define the followings in glossary : Profilepage, Tag.

**Comment by yilmazvolkan** [comment]
Our [requirements](https://github.com/bounswe/bounswe2018group1/wiki/Requirements) are reviewed and updated accordingly.
