### ISSUE TITLE
Create Mock-ups

### ISSUE THREAD

**Issue by cemal-aytekin-2015400126** [bounswe/bounswe2018group1#22]
We should create our mock-ups until 04.03.2018. 

* [x] Ece Ata
* [x] Cemal Aytekin
* [ ] Ahmet Yasin Alp
* [x] Volkan Yılmaz
* [x] Hatice Melike Ecevit
* [ ] Akın İlerle
* [ ] Öncel Keleş
* [ ] Deniz Etkar

**Comment by yilmazvolkan** [comment]
Our mockups for [android](https://github.com/bounswe/bounswe2018group1/wiki/android-mock) and [web](https://github.com/bounswe/bounswe2018group1/wiki/web-mock) are prepared and listed in the order of scenario.
