### ISSUE TITLE
Planning and Tool Use

### ISSUE THREAD

**Issue by cemal-aytekin-2015400126** [bounswe/bounswe2018group1#35]
Planning and Tool Use

According to -s's feedback:

1) Plans must be reviewed and adapted to improve effective development. I.e. Sunday night deadlines are not good as they do not allow midcourse intervention and prevent dissemination. It is not okay for one person to be aware of a given tasks and not others. Worse, when that one person is not present you are doomed.

2) Tools: We are expected to learn you to use software development tools effectively. 

* [ ] We should get good at documenting relevant information on the Wiki, review, an keep it up to date 

We need the practice of identifying, documenting, labeling, and tracking issues. It is not appropriate to have one person create all issues. It is not effective nor natural since issues arise all the time. An exception could be transferring to do items from a meeting to the issue system, which may be assigned to a given person. Alas, the responsible person will need to track them.

**Comment by yilmazvolkan** [comment]
It is disscussed on the meetings.
