### ISSUE TITLE
Choosing a name for application

### ISSUE THREAD

**Issue by cemal-aytekin-2015400126** [bounswe/bounswe2018group1#54]
I think we should find a name for our application.

**Comment by cemal-aytekin-2015400126** [comment]
iMemory
iStory
mmorey
hismory
mappory
backthen
tbt

**Comment by eceatata** [comment]
tbm: throwback memory

**Comment by hatice-ecevit-2016400138** [comment]
should we do a voting?

**Comment by yilmazvolkan** [comment]
I think we can choose one of them now

**Comment by eceatata** [comment]
Live Story

**Comment by eceatata** [comment]
Where is the doodle?
