### ISSUE TITLE
Requirement like "1.1.5. Homepage" etc. should be revised/removed

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2018group1#86]
User interface related decisions are almost never requirements. Only rarely there is some user interface level requirement that is mandated by the customer or law.

Homepages/tabs etc are not requirements. They are associated with designs to transform requirements into an application.

Please remove and/or revise so that user interface decisions are not in requirements.

**Comment by uskudarli** [comment]
i added a label for requirements. Revise accordingly. I used temp to indicate a temporary place holder.

**Comment by uskudarli** [comment]
I also added a milestone called phase1 to indicate the culmination of all the work that comes together due to end of semester.

**Comment by hatice-ecevit-2016400138** [comment]
our customer feedback from requirements which you can reach [here](https://github.com/bounswe/bounswe2018group1/issues/19) indicated that we should describe homepage, map view and profile pages thats why we added that terms but we will revise and update our requirements

**Comment by cantunca** [comment]
@uskudarli A map-like view that enables access to all memories in a specific region is an essential part of this project. Hence I stressed the importance of it in a way I envisioned it, exactly like how you describe it. But such an explanation may have misled the students, so I don’t blame them. The details about tabs are really close to the side of “how” rather than “what”. I believe the gist of the requirement is there, so a little revision to tune down the UI details would be sufficient to fix it. @uskudarli Do you agree?

**Comment by uskudarli** [comment]
Note: When you fix something and give a link, that is very good. But, it would be even better to give the reference to the revised items. That is why we give identifiers to requirements.

I have spoken with @cantunca as well.

I will make one final explanation. In the requirements you do not want to have any reference to user interface elements, like homepage, clicking, tabs, and so on.

The essence of that requriment is:

The user shall be able to see memories based on the locations of memories.

The user shall be able to search for memories based on location.

(Also, an important consideration is regarding memories that have multiple locations. For example, "When I was in high school, I used to take the boat from Istinye to Eminonu every morning. The same old man would sit at the same spot. We would have tea together most of the time. You know, that lousy but irreplaceable vapur tea. ...." (This memory has a **path** between two spots. And the memory is about traveling between two spots. ) Many memories are like that. So, the use shall be able to see geographical point, paths, and regions.

Again, refrain from expressing solutions to the requirements. And stick to the requirement themselves.

**Comment by uskudarli** [comment]
a meta-note: feedback is not provided to "blame" ... it is always meant as constructive criticism and co-learning.
